apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  selector:
    matchLabels:
      app: simple-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - image: aphiwe2020/simple-app:0.0.0
          name: simple-app
          ports:
            - containerPort: 7141
              name: simple-app
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app-svc
spec:
  ports:
    - port: 7141
      targetPort: 80
  selector:
    app: simple-app
  externalTrafficPolicy: Local
  type: LoadBalancer